### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by shizunge** [0xERR0R/blocky#1693]
Blocky version 0.25
Dashboard version: [57b1bdb](https://github.com/0xERR0R/blocky/commit/57b1bdbcea1da545e1717914b069ccc5eaf66dea)

3 panels showed `bad_data`

* Avg response time
* Cache hit/miss rate
* Prefetch count

![Image](https://github.com/user-attachments/assets/2e2fe09c-b6b4-4188-b5d1-207587065bef)

(Actually the dashboard had the same problem with blocky 0.24 too.)

**Comment by shizunge** [comment]
Also Denylist by group does not look correct.

`blocky_denylist_cache` should be `blocky_denylist_cache_entries` in v0.25

**Comment by niouniou49** [comment]
HI here
what is see compared to 0.24, the following panels are KO , i looked in details in formula
i was able to fix the others panels but 4 of them seems problematic, see below

- average resp time is KO -->"blocky_request_duration_ms_sum" and "blocky_request_duration_ms_count" are not working
- cache hit/miss ratio--->"blocky_cache_hit_count" and "blocky_cache_miss_count" are not working
- -prefetch hit ratio---> "blocky_prefetch_hit_count" and "blocky_cache_hit_count" are not working
- request duration (upstream)---> blocky_request_duration_ms_bucket

can you pleaseadvice on new items names if renamed in 0.25 compared to 0.24

**Comment by shizunge** [comment]
@niouniou49 based on the screenshot, it seems it is an old version dashboard. The panel orders are different.

The latest in the repo seems designed to work with both old and new metrics. But there are bugs in some query expressions.

**Comment by niouniou49** [comment]
hi here 
was someone able to correct the broken panel? specially the 'avg response time' ?

**Comment by 0xERR0R** [comment]
please try the latest version on master (https://github.com/0xERR0R/blocky/commit/a398516373f918792586a15953ea1bd4e75f6c9c)

**Comment by niouniou49** [comment]
Hi thanks a lot I fixed most of the errors except :Cache hit/Miss ratio, I did not manage to understand what’s wrong in the formula Any idea to correct it?Sent from my iPhoneOn 20 Jan 2025, at 21:24, Dimitri Herzog ***@***.***> wrote:﻿
please try the latest version on master (a398516)

**Comment by shizunge** [comment]
I see `No data` in some panel with 0.25
 
* `blocky_prefetchs_total` should be `blocky_prefetches_total`
* `blocky_prefetch_hit_count` should be `blocky_prefetch_hits_total`
* `blocky_cache_hit_count` should be `blocky_cache_hits_total`
* `blocky_cache_miss_count` should be `blocky_cache_misses_total`
* `blocky_request_duration_ms_bucket` should be `blocky_request_duration_seconds_bucket`

**Comment by niouniou49** [comment]
all good now thanks

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/b71c6bd7-8175-4956-b54d-74ab7ce85377" />

**Comment by shizunge** [comment]
This issue is not fixed, because the dashboard in the main branch does not work with v0.25.

Additionally if you want the dashboard to work for both 0.24 and 0.25, it needs extra effort.

**Comment by 0xERR0R** [comment]
@shizunge just updated queries, thanks for your hints. I think, support for 0.24 is not necessary, since working version can be checked out for 0.24 tag.
